// ============================================
// CLOTH DATA
//
// The Cloth Room's swatch library. Pure data — no drawing code. Tiles
// are rendered from these parameters by weave-engine.js, which is what
// makes a cloth three lines of data rather than a bespoke canvas
// function.
//
// ---- THE `verified` FLAG ----
//
// `verified: true`  — a real bunch from the mill's published range.
//   Carries `bunch` and whatever of `composition` / `weight` the mill
//   actually publishes, plus a `source` URL.
//
// `verified: false` — built to the mill's documented house style, and
//   named descriptively ("Charcoal Worsted Twill") rather than with an
//   invented bunch name. Carries NO composition, weight or bunch,
//   because a plausible-looking figure next to genuinely researched
//   mill data is worse than no figure at all.
//
// verify/audit.js enforces that rule, so the distinction cannot erode
// as the library grows. To promote a cloth: research it, add bunch +
// spec + source, flip the flag.
//
// ---- FIELDS ----
//
//   key            unique id, also the seed for the tile's texture
//   name           display name
//   mill           display name of the house
//   millPath       path into Cloth Origins — MUST resolve (audited)
//   guidePath      path to the weave's guide topic, where one fits
//   weave          one of WEAVE_GROUNDS in weave-engine.js
//   pattern        one of WEAVE_OVERLAYS in weave-engine.js
//   colour_family  filter facet: charcoal navy grey blue brown green tan cream black
//   weight_class   filter facet: light midweight heavy
//   ground         base colour hex
//   overlay        { type, colour, pitch, overcheck } — omit for plain cloths
//   character      one line of editorial voice
// ============================================

var CLOTH_LIBRARY = [

    // ============================================
    // ENGLAND — West Yorkshire and the West Country
    // ============================================

    {
        key: "fox_1772_classic_black",
        name: "1772 Flannel, Classic Black",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "1772 Flannel",
        composition: "Merino Lambswool / Cashmere",
        weight: "370 g",
        weave: "flannel",
        pattern: "none",
        colour_family: "black",
        weight_class: "heavy",
        ground: "#26262a",
        character: "The flannel Fox built its name on, with cashmere blended in. Matte, dense, and quietly formal.",
        verified: true,
        source: "https://foxflannel.com/products/ff26-1772-flannel-classic-black"
    },
    {
        key: "fox_classic_flannel_charcoal",
        name: "Classic Flannel, Charcoal",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Classic Flannel",
        composition: "100% Superfine Merino Wool",
        weight: "370 g",
        weave: "flannel",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "heavy",
        ground: "#3f4045",
        character: "Milled in Somerset since 1772. Soft, matte, and quietly authoritative under a chalk stripe.",
        verified: true,
        source: "https://foxflannel.com/collections/new-classic-flannel-mixed-weights"
    },
    {
        key: "fox_flannel_chalkstripe",
        name: "Grey Flannel Chalkstripe",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        weave: "flannel",
        pattern: "chalkstripe",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#585a60",
        overlay: { type: "chalkstripe", colour: "#e6e2d8", pitch: 24 },
        character: "The chalkstripe reads as drawn in soft pencil rather than printed — flannel takes a stripe better than any worsted.",
        verified: false
    },
    {
        key: "fox_worsted_flannel_navy",
        name: "Navy Worsted Flannel",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        weave: "flannel",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#2b3346",
        character: "Worsted-spun then milled: flannel's hand with a worsted's crispness of line.",
        verified: false
    },

    {
        key: "harrisons_frontier",
        name: "Frontier",
        mill: "Harrisons",
        millPath: ["cloth_origins", "suiting", "english", "harrisons"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Frontier",
        composition: "Worsted-Spun Merino Wool",
        weight: "300 g",
        weave: "twill",
        pattern: "none",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#55565c",
        character: "A versatile midweight superfine, woven in England for year-round wear.",
        verified: true,
        source: "https://www.harrisons1863.com/"
    },
    {
        key: "harrisons_moonbeam",
        name: "Moonbeam",
        mill: "Harrisons",
        millPath: ["cloth_origins", "suiting", "english", "harrisons"],
        bunch: "Moonbeam",
        composition: "75% Superfine Lambswool / 25% Angora",
        weight: "310 g",
        weave: "twill",
        pattern: "none",
        colour_family: "brown",
        weight_class: "midweight",
        ground: "#4e4239",
        character: "Angora blended into lambswool for a cashmere hand. Tailors beautifully and holds its shape.",
        verified: true,
        source: "https://www.harrisons1863.com/brand-portfolio/collection/harrisons-moonbeam/"
    },
    {
        key: "harrisons_herringbone_grey",
        name: "Grey Herringbone",
        mill: "Harrisons",
        millPath: ["cloth_origins", "suiting", "english", "harrisons"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#4f5157",
        character: "A classic English herringbone — close-set enough to read as texture at conversational distance.",
        verified: false
    },

    {
        key: "standeven_oxbridge_flannel",
        name: "Oxbridge Flannel",
        mill: "Standeven",
        millPath: ["cloth_origins", "suiting", "english", "standeven"],
        bunch: "Oxbridge Flannel",
        composition: "Super 120s Worsted-Woollen",
        weight: "370 g",
        weave: "flannel",
        pattern: "none",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#5c5e64",
        character: "Double-milled in Bradford and finished in Pennine water. Ultra-soft, with real substance.",
        verified: true,
        source: "https://www.standevenfabrics.co.uk/introducing-oxbridge-flannel/"
    },
    {
        key: "standeven_stonedale_flannel",
        name: "Stonedale Flannel",
        mill: "Standeven",
        millPath: ["cloth_origins", "suiting", "english", "standeven"],
        bunch: "Stonedale Flannel",
        composition: "100% RWS-Accredited Wool",
        weight: "450 g",
        weave: "flannel",
        pattern: "chalkstripe",
        colour_family: "charcoal",
        weight_class: "heavy",
        ground: "#3c3d43",
        overlay: { type: "chalkstripe", colour: "#ddd8cc", pitch: 24 },
        character: "Standeven's first fully Responsible Wool Standard collection. A serious winter weight.",
        verified: true,
        source: "https://www.standevenfabrics.co.uk/"
    },
    {
        key: "standeven_wool_linen_stone",
        name: "Stone Wool-Linen",
        mill: "Standeven",
        millPath: ["cloth_origins", "suiting", "english", "standeven"],
        guidePath: ["fabrics", "suiting", "wool_linen"],
        weave: "plain",
        pattern: "none",
        colour_family: "tan",
        weight_class: "light",
        ground: "#9a8f7c",
        character: "Linen's dry handle steadied by wool's recovery — the compromise that actually works in humidity.",
        verified: false
    },

    {
        key: "holland_sherry_crystal_springs",
        name: "Crystal Springs, Midnight",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Crystal Springs",
        composition: "Super 130s Worsted Merino",
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#242c40",
        character: "Plain and twill constructions in Super 130s worsted. The dependable dark suit.",
        verified: true,
        source: "https://apparel.hollandandsherry.com/en/hs1847ab-crystal-springs"
    },
    {
        key: "holland_sherry_glen_check",
        name: "Mock Glen Plaid",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        weave: "twill",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#585a5f",
        overlay: { type: "glen", colour: "#1d1f24", pitch: 24, overcheck: "#8a6d43" },
        character: "A glen check with a bronze overcheck — the pattern that makes a grey suit worth a second look.",
        verified: false
    },
    {
        key: "holland_sherry_windowpane_blue",
        name: "Blue Windowpane",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        weave: "twill",
        pattern: "windowpane",
        colour_family: "blue",
        weight_class: "light",
        ground: "#3c5170",
        overlay: { type: "windowpane", colour: "#d5cfc2", pitch: 32 },
        character: "A wide, quiet windowpane. Enough pattern to be a jacket, restrained enough to be a suit.",
        verified: false
    },

    {
        key: "scabal_summit",
        name: "Summit",
        mill: "Scabal",
        millPath: ["cloth_origins", "suiting", "english", "scabal"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Summit",
        weight: "280 g",
        weave: "plain",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#38393e",
        character: "A medium all-year weight with a full, flowing handle. Understated by design.",
        verified: true,
        source: "https://scabal.com/pages/summit-collection"
    },
    {
        key: "scabal_pinstripe_navy",
        name: "Navy Pinstripe",
        mill: "Scabal",
        millPath: ["cloth_origins", "suiting", "english", "scabal"],
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#232b3d",
        overlay: { type: "pinstripe", colour: "#dcd8cc", pitch: 12 },
        character: "A true single-yarn pinstripe: a dotted line at close range, a clean rule from across a room.",
        verified: false
    },

    {
        key: "huddersfield_fresco_slate",
        name: "Slate High-Twist",
        mill: "Huddersfield",
        millPath: ["cloth_origins", "suiting", "english", "huddersfield"],
        guidePath: ["fabrics", "suiting", "fresco"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#54607a",
        character: "Open, porous, high-twist. The cloth that made summer tailoring survivable in the tropics.",
        verified: false
    },
    {
        key: "huddersfield_fresco_navy",
        name: "Navy High-Twist",
        mill: "Huddersfield",
        millPath: ["cloth_origins", "suiting", "english", "huddersfield"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#2d3852",
        character: "Springy, crease-shedding, and built to breathe. A BBS staple for good reason.",
        verified: false
    },
    {
        key: "huddersfield_fresco_stripe",
        name: "High-Twist Chalkstripe",
        mill: "Huddersfield",
        millPath: ["cloth_origins", "suiting", "english", "huddersfield"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        weave: "plain",
        pattern: "chalkstripe",
        colour_family: "grey",
        weight_class: "light",
        ground: "#5b6478",
        overlay: { type: "chalkstripe", colour: "#e2ded2", pitch: 32 },
        character: "High-twist with a widely-set chalkstripe. Business cloth that does not wilt by midday.",
        verified: false
    },

    {
        key: "alfred_brown_worsted_navy",
        name: "Navy Super 120s",
        mill: "Alfred Brown",
        millPath: ["cloth_origins", "suiting", "english", "alfred_brown"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#252d42",
        character: "Leeds worsted, cut for the boardroom. Clean-faced with a firm, dependable drape.",
        verified: false
    },
    {
        key: "alfred_brown_birdseye",
        name: "Navy Birdseye",
        mill: "Alfred Brown",
        millPath: ["cloth_origins", "suiting", "english", "alfred_brown"],
        weave: "birdseye",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#28324a",
        character: "Tiny light eyes on a navy ground. Reads as solid at distance, alive up close.",
        verified: false
    },

    {
        key: "dugdale_worsted_charcoal",
        name: "Charcoal Worsted Twill",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3b3c41",
        character: "Huddersfield worsted of the old school — firm, honest, and built to be worn hard.",
        verified: false
    },
    {
        key: "dugdale_herringbone_brown",
        name: "Brown Herringbone",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#4a3d31",
        character: "A country herringbone in tobacco brown. Belongs with knitwear, not a tie.",
        verified: false
    },

    {
        key: "taylor_lodge_hopsack_navy",
        name: "Navy Hopsack",
        mill: "Taylor & Lodge",
        millPath: ["cloth_origins", "suiting", "english", "taylor_lodge"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#232f4b",
        character: "The definitive navy blazer cloth. Open basket weave, endlessly wearable.",
        verified: false
    },
    {
        key: "taylor_lodge_mohair_blend",
        name: "Charcoal Mohair Blend",
        mill: "Taylor & Lodge",
        millPath: ["cloth_origins", "suiting", "english", "taylor_lodge"],
        guidePath: ["fabrics", "suiting", "mohair_blends"],
        weave: "plain",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "light",
        ground: "#42434a",
        character: "Mohair's dry crispness and faint sheen. Holds a sharp edge in heat.",
        verified: false
    },

    {
        key: "abraham_moon_tweed_green",
        name: "Moss Tweed",
        mill: "Abraham Moon",
        millPath: ["cloth_origins", "suiting", "english", "abraham_moon"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "green",
        weight_class: "heavy",
        ground: "#414a3a",
        character: "Yorkshire tweed with a mossy melange. Rugged, but finished finely enough to tailor.",
        verified: false
    },
    {
        key: "abraham_moon_check_tan",
        name: "Tan Estate Check",
        mill: "Abraham Moon",
        millPath: ["cloth_origins", "suiting", "english", "abraham_moon"],
        weave: "twill",
        pattern: "glen",
        colour_family: "tan",
        weight_class: "heavy",
        ground: "#8b7a5f",
        overlay: { type: "glen", colour: "#3a3122", pitch: 24, overcheck: "#6a7a4a" },
        character: "An estate check with a green overcheck — the jacket that anchors a country wardrobe.",
        verified: false
    },

    {
        key: "joshua_ellis_cashmere_camel",
        name: "Camel Cashmere",
        mill: "Joshua Ellis",
        millPath: ["cloth_origins", "suiting", "english", "joshua_ellis"],
        weave: "flannel",
        pattern: "none",
        colour_family: "tan",
        weight_class: "heavy",
        ground: "#9c7f5b",
        character: "Cashmere raised to a soft bloom. An overcoat cloth that photographs beautifully.",
        verified: false
    },
    {
        key: "joshua_ellis_cashmere_navy",
        name: "Navy Cashmere",
        mill: "Joshua Ellis",
        millPath: ["cloth_origins", "suiting", "english", "joshua_ellis"],
        weave: "flannel",
        pattern: "none",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#2a3348",
        character: "Dense, weightless, and quietly expensive. Batley cashmere at its most restrained.",
        verified: false
    },

    // ============================================
    // ITALY — Biella, Milan and Naples
    // ============================================

    {
        key: "vbc_perennial",
        name: "Perennial",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Perennial",
        composition: "100% Merino Wool, Super 110s",
        weight: "260-280 g",
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#28304a",
        character: "VBC's all-season workhorse. Enough substance to drape, never enough to overheat.",
        verified: true,
        source: "https://vitalebarberiscanonico.com/collection/fabrics/"
    },
    {
        key: "vbc_hopsack_blue",
        name: "Blue Hopsack",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "blue",
        weight_class: "light",
        ground: "#2f4468",
        character: "Biella hopsack in a lifted mid-blue. Open enough to read as summer, structured enough to tailor.",
        verified: false
    },
    {
        key: "vbc_birdseye_charcoal",
        name: "Charcoal Birdseye",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        weave: "birdseye",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3a3b42",
        character: "A birdseye so fine it reads as texture rather than pattern. The quiet alternative to plain charcoal.",
        verified: false
    },
    {
        key: "vbc_glen_grey",
        name: "Grey Glen Check",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        weave: "twill",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#5a5c62",
        overlay: { type: "glen", colour: "#22242a", pitch: 24 },
        character: "Glenurquhart without an overcheck — the restrained reading of a loud pattern.",
        verified: false
    },

    {
        key: "loro_piana_tasmanian",
        name: "Tasmanian",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Tasmanian 691",
        composition: "100% Wool, Super 150s",
        weight: "250 g",
        weave: "plain",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "light",
        ground: "#3d3e45",
        character: "Only 250 grams and still year-round. The benchmark for lightweight worsted.",
        verified: true,
        source: "https://senszio.com/loro-piana-tasmanian-691-collezione-suit-italian-fabrics-all-year-round/"
    },
    {
        key: "loro_piana_zelander",
        name: "Zelander",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        bunch: "Zelander",
        composition: "100% Superfine Merino Wool",
        weight: "360 g",
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#26304a",
        character: "New Zealand merino with natural stretch, at a structured jacket weight.",
        verified: true,
        source: "https://astorandblack.com/shop/fabric-bolt-specials/lp-zelander"
    },
    {
        key: "loro_piana_four_seasons",
        name: "Four Seasons",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Four Seasons",
        composition: "100% Wool, Super 130s",
        weave: "twill",
        pattern: "none",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#53545b",
        character: "A touch more weight than Tasmanian, which makes it the cooler-season pick.",
        verified: true,
        source: "https://qcontrary.com/fabric-series-loro-piana-fabrics/"
    },
    {
        key: "loro_piana_wish_navy",
        name: "Navy Superfine Twill",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#222a3f",
        character: "Superfine merino with a faint lustre. Formal without ever looking stiff.",
        verified: false
    },

    {
        key: "solbiati_art_du_lin",
        name: "Art du Lin",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Art du Lin",
        composition: "100% Linen",
        weight: "410-420 g",
        weave: "plain",
        pattern: "none",
        colour_family: "tan",
        weight_class: "heavy",
        ground: "#a2957c",
        character: "Three-ply twisted yarns: springy and raw on the reverse, invitingly soft on the face.",
        verified: true,
        source: "https://www.solbiati.it/en/fabrics/art-du-lin.html"
    },
    {
        key: "solbiati_linen_cream",
        name: "Cream Linen",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        weave: "plain",
        pattern: "none",
        colour_family: "cream",
        weight_class: "light",
        ground: "#c9bda4",
        character: "Northern European flax, woven fine. Creases honestly — that is the point.",
        verified: false
    },
    {
        key: "solbiati_wool_silk_linen",
        name: "Wool-Silk-Linen, Sand",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "wool_silk_linen"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "tan",
        weight_class: "light",
        ground: "#a0947a",
        character: "The three-fibre blend that behaves better than any one of them alone.",
        verified: false
    },

    {
        key: "reda_baronet_130s",
        name: "Baronet Super 130s",
        mill: "Reda",
        millPath: ["cloth_origins", "suiting", "italian", "reda"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Baronet",
        composition: "100% Wool, Super 130s",
        weight: "260 g",
        weave: "plain",
        pattern: "none",
        colour_family: "black",
        weight_class: "midweight",
        ground: "#1c2436",
        character: "Extra-fine Biella merino with a smooth, even face. Evening cloth without the shine.",
        verified: true,
        source: "https://www.reda1865.com/row/listing"
    },
    {
        key: "reda_flexo",
        name: "Flexo",
        mill: "Reda",
        millPath: ["cloth_origins", "suiting", "italian", "reda"],
        bunch: "Flexo",
        composition: "Merino Wool / ROICA V550 Elastomer",
        weave: "twill",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3e3f46",
        character: "Merino meeting a sustainable stretch yarn. Recovery for long days and long flights.",
        verified: true,
        source: "https://www.reda1865.com/row/state-of-the-art-technology"
    },
    {
        key: "reda_herringbone_blue",
        name: "Blue Herringbone",
        mill: "Reda",
        millPath: ["cloth_origins", "suiting", "italian", "reda"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "blue",
        weight_class: "light",
        ground: "#33456a",
        character: "A fine chevron in mid-blue. Texture that survives a video call.",
        verified: false
    },

    {
        key: "drapers_ascot_two_ply",
        name: "Ascot Two Ply",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "two_ply"],
        bunch: "Ascot",
        composition: "Worsted Wool, 21 Micron",
        weight: "250 g (8 oz)",
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#5b5d64",
        character: "The lightest of the Ascot weaves. Dry, energetic hand from deliberately thicker wools.",
        verified: true,
        source: "https://drapersitaly.it/gb-en/collection/bunch/ascot/"
    },
    {
        key: "drapers_ascot_four_ply",
        name: "Ascot Four Ply",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "four_ply"],
        bunch: "Ascot Two, Four and Six Ply",
        composition: "Worsted Wool, 21 Micron",
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#252e46",
        character: "Four-ply gives durability, crease resistance and a drape the two-ply cannot reach.",
        verified: true,
        source: "https://drapersitaly.it/gb-en/collection/bunch/ascot-two-four-and-six-ply/"
    },
    {
        key: "drapers_ascot_six_ply",
        name: "Ascot Six Ply",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "six_ply"],
        bunch: "Ascot Two, Four and Six Ply",
        composition: "Worsted Wool, 21 Micron",
        weave: "twill",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "heavy",
        ground: "#383940",
        character: "Six-ply, woven by VBC for Drapers. Full-bodied and unmistakably substantial.",
        verified: true,
        source: "https://drapersitaly.it/gb-en/collection/bunch/ascot-two-four-and-six-ply/"
    },

    {
        key: "drago_super_130s",
        name: "Super 130s, Ash",
        mill: "Drago",
        millPath: ["cloth_origins", "suiting", "italian", "drago"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#63656c",
        character: "Biella superfine with a soft, fluid drape. Cuts beautifully in a soft-shouldered jacket.",
        verified: false
    },
    {
        key: "drago_hopsack_green",
        name: "Olive Hopsack",
        mill: "Drago",
        millPath: ["cloth_origins", "suiting", "italian", "drago"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "green",
        weight_class: "light",
        ground: "#4a5240",
        character: "Olive is the third neutral. Reads as considered rather than safe.",
        verified: false
    },

    {
        key: "zegna_trofeo_navy",
        name: "Navy Superfine",
        mill: "Zegna",
        millPath: ["cloth_origins", "suiting", "italian", "zegna"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#242b40",
        character: "Trivero superfine with a faint sheen. The Italian reading of a business suit.",
        verified: false
    },
    {
        key: "zegna_pinstripe_charcoal",
        name: "Charcoal Pinstripe",
        mill: "Zegna",
        millPath: ["cloth_origins", "suiting", "italian", "zegna"],
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#35363c",
        overlay: { type: "pinstripe", colour: "#cdc8bb", pitch: 16 },
        character: "Widely spaced pinstripe on charcoal. Formal, but not costume.",
        verified: false
    },

    {
        key: "cerruti_twill_blue",
        name: "Blue Twill",
        mill: "Cerruti",
        millPath: ["cloth_origins", "suiting", "italian", "cerruti"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#31456b",
        character: "Biella cloth with a fashion edge. A clearer blue than the traditional navy.",
        verified: false
    },
    {
        key: "cerruti_windowpane_grey",
        name: "Grey Windowpane",
        mill: "Cerruti",
        millPath: ["cloth_origins", "suiting", "italian", "cerruti"],
        weave: "plain",
        pattern: "windowpane",
        colour_family: "grey",
        weight_class: "light",
        ground: "#5e6067",
        overlay: { type: "windowpane", colour: "#d8d3c6", pitch: 24 },
        character: "A tighter windowpane than most. Structured enough for a full suit.",
        verified: false
    },

    {
        key: "piacenza_cashmere_grey",
        name: "Grey Cashmere Blend",
        mill: "Piacenza",
        millPath: ["cloth_origins", "suiting", "italian", "piacenza"],
        weave: "flannel",
        pattern: "none",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#5a5b61",
        character: "Piedmont cashmere, milled soft. The jacket you reach for without thinking.",
        verified: false
    },
    {
        key: "piacenza_wool_silk_brown",
        name: "Chestnut Wool-Silk",
        mill: "Piacenza",
        millPath: ["cloth_origins", "suiting", "italian", "piacenza"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "brown",
        weight_class: "light",
        ground: "#6a5340",
        character: "Silk lifts the brown out of flatness without tipping into shine.",
        verified: false
    },

    {
        key: "marzotto_worsted_navy",
        name: "Navy Worsted",
        mill: "Marzotto",
        millPath: ["cloth_origins", "suiting", "italian", "marzotto"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#252d43",
        character: "Veneto worsted at a sensible weight. Unshowy, reliable, everywhere for a reason.",
        verified: false
    },
    {
        key: "marzotto_birdseye_blue",
        name: "Blue Birdseye",
        mill: "Marzotto",
        millPath: ["cloth_origins", "suiting", "italian", "marzotto"],
        weave: "birdseye",
        pattern: "none",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#2e3d5c",
        character: "Birdseye in a lighter blue — a suit that survives daylight.",
        verified: false
    },

    {
        key: "tallia_delfino_mohair",
        name: "Midnight Mohair",
        mill: "Tallia di Delfino",
        millPath: ["cloth_origins", "suiting", "italian", "tallia_delfino"],
        guidePath: ["fabrics", "suiting", "mohair_blends"],
        weave: "plain",
        pattern: "none",
        colour_family: "black",
        weight_class: "light",
        ground: "#1f2130",
        character: "Kid mohair blended into wool. Crisp, dry, faintly luminous under evening light.",
        verified: false
    },
    {
        key: "tallia_delfino_fresco_grey",
        name: "Grey High-Twist",
        mill: "Tallia di Delfino",
        millPath: ["cloth_origins", "suiting", "italian", "tallia_delfino"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#666870",
        character: "High-twist with Neapolitan openness. Built for heat, not for the office radiator.",
        verified: false
    },

    {
        key: "guabello_twill_charcoal",
        name: "Charcoal Twill",
        mill: "Guabello",
        millPath: ["cloth_origins", "suiting", "italian", "guabello"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3a3b41",
        character: "A firm Biella twill. Holds a crease and a shoulder line equally well.",
        verified: false
    },
    {
        key: "guabello_glen_navy",
        name: "Navy Glen Check",
        mill: "Guabello",
        millPath: ["cloth_origins", "suiting", "italian", "guabello"],
        weave: "twill",
        pattern: "glen",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#2c3550",
        overlay: { type: "glen", colour: "#161b2a", pitch: 24, overcheck: "#a98a5c" },
        character: "Glen check pitched dark enough to wear as a suit rather than a statement.",
        verified: false
    },

    {
        key: "e_thomas_wool_silk",
        name: "Wool-Silk, Slate",
        mill: "E. Thomas",
        millPath: ["cloth_origins", "suiting", "italian", "e_thomas"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#5d616b",
        character: "Silk in the weft gives a subtle glow that photographs far better than it describes.",
        verified: false
    },
    {
        key: "e_thomas_linen_blend_blue",
        name: "Blue Wool-Linen",
        mill: "E. Thomas",
        millPath: ["cloth_origins", "suiting", "italian", "e_thomas"],
        guidePath: ["fabrics", "suiting", "wool_linen"],
        weave: "plain",
        pattern: "none",
        colour_family: "blue",
        weight_class: "light",
        ground: "#41577a",
        character: "Linen texture with wool's memory. A resort suit that still looks tailored on day three.",
        verified: false
    },

    {
        key: "botto_giuseppe_merino_navy",
        name: "Navy Merino",
        mill: "Botto Giuseppe",
        millPath: ["cloth_origins", "suiting", "italian", "botto_giuseppe"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#232b41",
        character: "Traceable merino spun in Valle Mosso. Clean-faced and unfussy.",
        verified: false
    },
    {
        key: "botto_giuseppe_herringbone_charcoal",
        name: "Charcoal Herringbone",
        mill: "Botto Giuseppe",
        millPath: ["cloth_origins", "suiting", "italian", "botto_giuseppe"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3c3d44",
        character: "A close chevron on charcoal. The safest interesting cloth in the room.",
        verified: false
    },

    {
        key: "zignone_hopsack_navy",
        name: "Navy Open Hopsack",
        mill: "Zignone",
        millPath: ["cloth_origins", "suiting", "italian", "zignone"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#26314e",
        character: "A generously open basket weave. Air moves through it, which is the whole idea.",
        verified: false
    },
    {
        key: "zignone_twill_tan",
        name: "Tan Cotton Twill",
        mill: "Zignone",
        millPath: ["cloth_origins", "suiting", "italian", "zignone"],
        weave: "twill",
        pattern: "none",
        colour_family: "tan",
        weight_class: "midweight",
        ground: "#8e7a5c",
        character: "Cotton twill with a soft finish. Chino energy, tailored properly.",
        verified: false
    },

    {
        key: "ariston_linen_navy",
        name: "Navy Linen",
        mill: "Ariston",
        millPath: ["cloth_origins", "suiting", "italian", "ariston"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#2f3d55",
        character: "Neapolitan linen, dyed deep. Rumples with intent rather than by accident.",
        verified: false
    },
    {
        key: "ariston_seersucker_blue",
        name: "Blue Seersucker",
        mill: "Ariston",
        millPath: ["cloth_origins", "suiting", "italian", "ariston"],
        guidePath: ["fabrics", "suiting", "seersucker_suiting"],
        weave: "plain",
        pattern: "pinstripe",
        colour_family: "blue",
        weight_class: "light",
        ground: "#54749c",
        overlay: { type: "pinstripe", colour: "#f0ece2", pitch: 8 },
        character: "Puckered so it lifts off the skin. The most practical unserious cloth there is.",
        verified: false
    },

    {
        key: "caccioppoli_wool_silk_linen",
        name: "Wool-Silk-Linen, Clay",
        mill: "Caccioppoli",
        millPath: ["cloth_origins", "suiting", "italian", "caccioppoli"],
        guidePath: ["fabrics", "suiting", "wool_silk_linen"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "brown",
        weight_class: "light",
        ground: "#7d6350",
        character: "Naples' favourite summer blend, in a warm clay that flatters most complexions.",
        verified: false
    },
    {
        key: "caccioppoli_fresco_navy",
        name: "Navy Fresco",
        mill: "Caccioppoli",
        millPath: ["cloth_origins", "suiting", "italian", "caccioppoli"],
        guidePath: ["fabrics", "suiting", "fresco"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#2a3550",
        character: "Open-weave high-twist from a merchant who understands heat.",
        verified: false
    },

    // ============================================
    // FRANCE
    // ============================================

    {
        key: "dormeuil_amadeus_365",
        name: "Amadeus 365",
        mill: "Dormeuil",
        millPath: ["cloth_origins", "suiting", "french", "dormeuil"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Amadeus 365",
        composition: "100% Wool",
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#262e45",
        character: "Dormeuil's year-round staple, built to be worn every month of the year.",
        verified: true,
        source: "https://dormeuil.com/collections/fabric-amadeus-365"
    },
    {
        key: "dormeuil_tonik_charcoal",
        name: "Charcoal Mohair Tonik",
        mill: "Dormeuil",
        millPath: ["cloth_origins", "suiting", "french", "dormeuil"],
        guidePath: ["fabrics", "suiting", "mohair_blends"],
        weave: "plain",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "light",
        ground: "#3d3e47",
        character: "The mohair blend that defined a decade of sharp tailoring. Dry, crisp, faintly metallic.",
        verified: false
    },
    {
        key: "dormeuil_glen_grey",
        name: "Grey Prince of Wales",
        mill: "Dormeuil",
        millPath: ["cloth_origins", "suiting", "french", "dormeuil"],
        weave: "twill",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#57595f",
        overlay: { type: "glen", colour: "#1f2126", pitch: 32, overcheck: "#7d5a8a" },
        character: "A large-scale Prince of Wales with a lilac overcheck. Confident, and knows it.",
        verified: false
    },

    {
        key: "hellard_worsted_blue",
        name: "French Blue Worsted",
        mill: "Maison Hellard",
        millPath: ["cloth_origins", "suiting", "french", "hellard"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#35476d",
        character: "A distinctly French blue — lighter and cleaner than an English navy.",
        verified: false
    },
    {
        key: "hellard_flannel_stone",
        name: "Stone Flannel",
        mill: "Maison Hellard",
        millPath: ["cloth_origins", "suiting", "french", "hellard"],
        weave: "flannel",
        pattern: "none",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#7b7a74",
        character: "A pale flannel, which takes nerve. Worth it against a dark jacket.",
        verified: false
    },

    // ============================================
    // SCOTLAND AND IRELAND
    // ============================================

    {
        key: "johnstons_cashmere_charcoal",
        name: "Charcoal Cashmere",
        mill: "Johnstons of Elgin",
        millPath: ["cloth_origins", "suiting", "scottish", "johnstons"],
        weave: "flannel",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "heavy",
        ground: "#414248",
        character: "Elgin cashmere, washed in Spey water. Soft in a way that reads on camera.",
        verified: false
    },
    {
        key: "johnstons_estate_tweed",
        name: "Heather Estate Tweed",
        mill: "Johnstons of Elgin",
        millPath: ["cloth_origins", "suiting", "scottish", "johnstons"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        weave: "herringbone",
        pattern: "glen",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#5c4b3f",
        overlay: { type: "glen", colour: "#2e241d", pitch: 32, overcheck: "#7a5a72" },
        character: "Estate tweed with a heather overcheck. Built for weather, cut for town.",
        verified: false
    },

    {
        key: "lovat_tweed_green",
        name: "Lovat Green Tweed",
        mill: "Lovat Mill",
        millPath: ["cloth_origins", "suiting", "scottish", "lovat"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "green",
        weight_class: "heavy",
        ground: "#4a5343",
        character: "The green that gave the mill its name. Melange enough to hide a Scottish autumn.",
        verified: false
    },
    {
        key: "lovat_tweed_check",
        name: "Border Check",
        mill: "Lovat Mill",
        millPath: ["cloth_origins", "suiting", "scottish", "lovat"],
        weave: "twill",
        pattern: "windowpane",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#6b5744",
        overlay: { type: "windowpane", colour: "#d9cdb4", pitch: 32 },
        character: "A Borders check with an open pane. Country jacket, not country costume.",
        verified: false
    },

    {
        key: "magee_donegal_flecked",
        name: "Flecked Donegal",
        mill: "Magee",
        millPath: ["cloth_origins", "suiting", "irish", "magee"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#565a58",
        character: "Donegal's signature coloured neps scattered through a grey ground. Never quite one colour.",
        verified: false
    },
    {
        key: "magee_donegal_herringbone",
        name: "Donegal Herringbone",
        mill: "Magee",
        millPath: ["cloth_origins", "suiting", "irish", "magee"],
        weave: "herringbone",
        pattern: "none",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#52463a",
        character: "Handwoven character at mill scale. Warm, dry, and forgiving of a hard week.",
        verified: false
    },
    {
        key: "magee_linen_natural",
        name: "Natural Irish Linen",
        mill: "Magee",
        millPath: ["cloth_origins", "suiting", "irish", "magee"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        weave: "plain",
        pattern: "none",
        colour_family: "cream",
        weight_class: "light",
        ground: "#c4b79c",
        character: "Undyed Irish linen. The most honest cloth in the room.",
        verified: false
    },

    // ============================================
    // SINGAPORE — home
    // ============================================

    {
        key: "paladino_tropical_navy",
        name: "Tropical Navy",
        mill: "Officine Paladino",
        millPath: ["cloth_origins", "suiting", "singaporean", "officine_paladino"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#2b3552",
        character: "Chosen for this climate first. High-twist, open, and unbothered by an equatorial afternoon.",
        verified: false
    },
    {
        key: "paladino_hopsack_stone",
        name: "Stone Hopsack",
        mill: "Officine Paladino",
        millPath: ["cloth_origins", "suiting", "singaporean", "officine_paladino"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "tan",
        weight_class: "light",
        ground: "#9c9280",
        character: "A pale hopsack that works against skin tones here rather than in a Milanese autumn.",
        verified: false
    },
    {
        key: "paladino_wool_silk_linen_grey",
        name: "Wool-Silk-Linen, Ash",
        mill: "Officine Paladino",
        millPath: ["cloth_origins", "suiting", "singaporean", "officine_paladino"],
        guidePath: ["fabrics", "suiting", "wool_silk_linen"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#6e6f6a",
        character: "Three fibres balancing each other out. The most useful jacket cloth in a tropical wardrobe.",
        verified: false
    },
    {
        key: "paladino_cotton_rust",
        name: "Rust Cotton",
        mill: "Officine Paladino",
        millPath: ["cloth_origins", "suiting", "singaporean", "officine_paladino"],
        weave: "twill",
        pattern: "none",
        colour_family: "brown",
        weight_class: "midweight",
        ground: "#8a5a41",
        character: "A bold rust in cotton twill. Trousers that carry a plain jacket entirely.",
        verified: false
    },

    // ============================================
    // FURTHER DEPTH
    // Second and third colourways for the houses that carry a BBS
    // wardrobe most often, so filtering by colour returns a real
    // choice rather than a single cloth per facet.
    // ============================================

    {
        key: "fox_flannel_mid_grey",
        name: "Mid Grey Flannel",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        weave: "flannel",
        pattern: "none",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#6b6c70",
        character: "The mid grey flannel trouser. Pairs with almost every jacket in a wardrobe.",
        verified: false
    },
    {
        key: "vbc_worsted_black",
        name: "Black Worsted",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "black",
        weight_class: "midweight",
        ground: "#1e1f24",
        character: "True black, matte-finished. Kept for the occasions that genuinely call for it.",
        verified: false
    },
    {
        key: "vbc_wool_linen_olive",
        name: "Olive Wool-Linen",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "wool_linen"],
        weave: "plain",
        pattern: "none",
        colour_family: "green",
        weight_class: "light",
        ground: "#5d6349",
        character: "Olive with linen slub running through it. Warmer than grey, quieter than brown.",
        verified: false
    },
    {
        key: "loro_piana_hopsack_charcoal",
        name: "Charcoal Hopsack",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "light",
        ground: "#42434a",
        character: "Hopsack pitched dark. A blazer that reads formal without a navy cliche.",
        verified: false
    },
    {
        key: "reda_worsted_grey",
        name: "Light Grey Worsted",
        mill: "Reda",
        millPath: ["cloth_origins", "suiting", "italian", "reda"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#74767d",
        character: "A pale grey that stays crisp in humidity. Summer business cloth.",
        verified: false
    },
    {
        key: "holland_sherry_flannel_navy",
        name: "Navy Flannel",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        weave: "flannel",
        pattern: "none",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#2c3346",
        character: "Navy flannel: softer than worsted, more forgiving, and warmer in every sense.",
        verified: false
    },
    {
        key: "standeven_worsted_blue",
        name: "Airforce Worsted",
        mill: "Standeven",
        millPath: ["cloth_origins", "suiting", "english", "standeven"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "twill",
        pattern: "none",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#3b5069",
        character: "A greyed-off blue. More interesting than navy, still entirely wearable to work.",
        verified: false
    },
    {
        key: "harrisons_windowpane_charcoal",
        name: "Charcoal Windowpane",
        mill: "Harrisons",
        millPath: ["cloth_origins", "suiting", "english", "harrisons"],
        weave: "twill",
        pattern: "windowpane",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3d3e44",
        overlay: { type: "windowpane", colour: "#cfc9bb", pitch: 32 },
        character: "A pale pane on charcoal. The check for people who claim not to wear checks.",
        verified: false
    },
    {
        key: "dormeuil_worsted_grey",
        name: "Silver Grey Worsted",
        mill: "Dormeuil",
        millPath: ["cloth_origins", "suiting", "french", "dormeuil"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        weave: "plain",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#7a7c83",
        character: "Silver grey with a faint lustre. Daytime formal, and a favourite for weddings.",
        verified: false
    },
    {
        key: "drapers_hopsack_brown",
        name: "Tobacco Hopsack",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "brown",
        weight_class: "light",
        ground: "#6b543c",
        character: "Tobacco brown in an open weave. The odd jacket that makes grey trousers look deliberate.",
        verified: false
    },
    {
        key: "caccioppoli_cotton_cream",
        name: "Cream Cotton",
        mill: "Caccioppoli",
        millPath: ["cloth_origins", "suiting", "italian", "caccioppoli"],
        weave: "twill",
        pattern: "none",
        colour_family: "cream",
        weight_class: "midweight",
        ground: "#c2b596",
        character: "Cream cotton twill, garment-washed soft. Unstructured tailoring's natural partner.",
        verified: false
    },
    {
        key: "solbiati_linen_green",
        name: "Sage Linen",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        weave: "plain",
        pattern: "none",
        colour_family: "green",
        weight_class: "light",
        ground: "#7d8768",
        character: "A dusty sage linen. Reads as considered in a room full of beige.",
        verified: false
    },
    {
        key: "zegna_hopsack_grey",
        name: "Grey Hopsack",
        mill: "Zegna",
        millPath: ["cloth_origins", "suiting", "italian", "zegna"],
        guidePath: ["fabrics", "suiting", "hopsack"],
        weave: "hopsack",
        pattern: "none",
        colour_family: "grey",
        weight_class: "light",
        ground: "#63656b",
        character: "Grey hopsack, finely woven. A jacket that works with denim and with flannel both.",
        verified: false
    },
    {
        key: "drago_birdseye_black",
        name: "Black Birdseye",
        mill: "Drago",
        millPath: ["cloth_origins", "suiting", "italian", "drago"],
        weave: "birdseye",
        pattern: "none",
        colour_family: "black",
        weight_class: "light",
        ground: "#1f2027",
        character: "Black with the faintest light eye. Depth where a flat black would go dead.",
        verified: false
    },
    {
        key: "piacenza_flannel_navy",
        name: "Navy Cashmere Flannel",
        mill: "Piacenza",
        millPath: ["cloth_origins", "suiting", "italian", "piacenza"],
        weave: "flannel",
        pattern: "none",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#2a3145",
        character: "Cashmere milled into a navy flannel. The warmest thing here, and the softest.",
        verified: false
    },
    {
        key: "magee_tweed_blue",
        name: "Blue Donegal",
        mill: "Magee",
        millPath: ["cloth_origins", "suiting", "irish", "magee"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        weave: "plain",
        pattern: "none",
        colour_family: "blue",
        weight_class: "heavy",
        ground: "#3f4d64",
        character: "Donegal neps over a blue ground. Country cloth that behaves in a city.",
        verified: false
    },
    {
        key: "paladino_linen_white",
        name: "Chalk Linen",
        mill: "Officine Paladino",
        millPath: ["cloth_origins", "suiting", "singaporean", "officine_paladino"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        weave: "plain",
        pattern: "none",
        colour_family: "cream",
        weight_class: "light",
        ground: "#d3caB4",
        character: "Near-white linen. Reserved for the tropics, where it stops looking like a costume.",
        verified: false
    },

    // Researched bunches, July 2026. Every entry below carries the bunch,
    // the published spec and the page it was read from.
    {
        key: "dugdale_royal_classic_herringbone",
        name: "Royal Classic, Airforce Herringbone",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Royal Classic",
        composition: "100% Wool",
        weight: "340 g",
        weave: "herringbone",
        pattern: "none",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#3d4859",
        character: "Bunch 182, woven in Huddersfield. Dugdale's compact finish, so the herringbone only shows at handshake distance.",
        verified: true,
        source: "https://www.dugdalebros.com/collections/royal-classic/"
    },
    {
        key: "dugdale_royal_classic_ropestripe",
        name: "Royal Classic, Black Ropestripe",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Royal Classic",
        composition: "100% Wool",
        weight: "340 g",
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "black",
        weight_class: "midweight",
        ground: "#1b1b1e",
        overlay: { type: "pinstripe", colour: "#cfcabc", pitch: 16 },
        character: "A wide rope stripe on black. The most formal cloth in a bunch of formal cloths.",
        verified: true,
        source: "https://www.dugdalebros.com/collections/royal-classic/"
    },
    {
        key: "dugdale_fine_worsted_pow",
        name: "New Fine Worsted, Prince of Wales",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        bunch: "New Fine Worsted Classic",
        composition: "100% Wool",
        weight: "300 g",
        weave: "plain",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#6d6d69",
        overlay: { type: "glen", colour: "#2a2a2c", pitch: 24, overcheck: "#4a6ea0" },
        character: "Black and white check under a blue overcheck. Bunch 140 is an uptwisted open weave — the range Dugdale trace to the cream uniforms of Raffles.",
        verified: true,
        source: "https://www.dugdalebros.com/collections/new-fine-worsted-classic/"
    },
    {
        key: "dugdale_fine_worsted_pinstripe",
        name: "New Fine Worsted, Red Pin Stripe",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        bunch: "New Fine Worsted Classic",
        composition: "100% Wool",
        weight: "300 g",
        weave: "plain",
        pattern: "pinstripe",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#232b3f",
        overlay: { type: "pinstripe", colour: "#a8443f", pitch: 12 },
        character: "A red pin stripe on navy, in a cloth built for breathability and crease recovery. Wear it where the air conditioning is unreliable.",
        verified: true,
        source: "https://www.dugdalebros.com/collections/new-fine-worsted-classic/"
    },
    {
        key: "dugdale_town_chalkstripe",
        name: "English & Town, Black Chalk Stripe",
        mill: "Dugdale Bros",
        millPath: ["cloth_origins", "suiting", "english", "dugdale"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "English & Town Classics",
        composition: "100% Wool",
        weight: "400 g",
        weave: "flannel",
        pattern: "chalkstripe",
        colour_family: "black",
        weight_class: "heavy",
        ground: "#1e1e21",
        overlay: { type: "chalkstripe", colour: "#ddd8cc", pitch: 24 },
        character: "Superfine Australian merino, semi-milled to a winter weight. In continuous production since 1953.",
        verified: true,
        source: "https://www.dugdalebros.com/collections/english-town-classics/"
    },
    {
        key: "huddersfield_crown_classic_glen",
        name: "Crown Classic, Glen Check",
        mill: "Huddersfield",
        millPath: ["cloth_origins", "suiting", "english", "huddersfield"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Crown Classic",
        composition: "100% Wool",
        weight: "12-13 oz",
        weave: "twill",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "heavy",
        ground: "#5c5c5a",
        overlay: { type: "glen", colour: "#26262a", pitch: 24 },
        character: "Glen checks and sharkskins with real structure. The mill has held a Royal Warrant since the 1930s.",
        verified: true,
        source: "https://njb.com.sg/huddersfield-fine-worsteds"
    },
    {
        key: "huddersfield_irish_linen",
        name: "Casual Irish Linen",
        mill: "Huddersfield",
        millPath: ["cloth_origins", "suiting", "english", "huddersfield"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Casual Irish Linen",
        composition: "100% Irish Linen",
        weave: "herringbone",
        pattern: "none",
        colour_family: "cream",
        weight_class: "midweight",
        ground: "#cfc4ab",
        character: "Plains and herringbones in sun-washed shades. Linen for a climate that never does winter.",
        verified: true,
        source: "https://njb.com.sg/huddersfield-fine-worsteds"
    },
    {
        key: "lovat_teviot",
        name: "The Teviot",
        mill: "Lovat Mill",
        millPath: ["cloth_origins", "suiting", "scottish", "lovat"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        bunch: "The Teviot",
        composition: "100% Wool",
        weight: "430 g (13/14 oz)",
        weave: "twill",
        pattern: "windowpane",
        colour_family: "green",
        weight_class: "heavy",
        ground: "#4b5241",
        overlay: { type: "windowpane", colour: "#c9b98f", pitch: 32 },
        character: "First woven in the early 1900s: worsted merino against cheviot woollen yarn, which is why it stays light for its weight.",
        verified: true,
        source: "https://lovatmill.com/bunches/the-teviot/"
    },
    {
        key: "lovat_kirkton",
        name: "The Kirkton",
        mill: "Lovat Mill",
        millPath: ["cloth_origins", "suiting", "scottish", "lovat"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        bunch: "The Kirkton",
        composition: "100% Wool",
        weight: "500 g (16 oz)",
        weave: "herringbone",
        pattern: "none",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#6b5c45",
        character: "Single cheviot, crisp in the hand. A jacketing cloth that takes bold colour mixtures without shouting.",
        verified: true,
        source: "https://lovatmill.com/bunches/the-kirkton/"
    },
    {
        key: "lovat_ettrick",
        name: "The Ettrick",
        mill: "Lovat Mill",
        millPath: ["cloth_origins", "suiting", "scottish", "lovat"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        bunch: "The Ettrick",
        composition: "100% Wool",
        weight: "640 g (21 oz)",
        weave: "twill",
        pattern: "none",
        colour_family: "green",
        weight_class: "heavy",
        ground: "#3f4735",
        character: "Twenty-one ounces of sporting tweed, firmly woven and finished showerproof. Woven in Hawick, in the Scottish Borders.",
        verified: true,
        source: "https://lovatmill.com/bunches/the-ettrick/"
    },
    {
        key: "holland_sherry_royal_mile",
        name: "Royal Mile 1976",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Royal Mile 1976",
        composition: "Super 140s Merino Wool",
        weave: "twill",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#575a5e",
        overlay: { type: "glen", colour: "#24262a", pitch: 24 },
        character: "A traditional serge construction — sharkskins, glen plaids and pinstripes in one all-season book.",
        verified: true,
        source: "https://njb.com.sg/holland-sherry"
    },
    {
        key: "holland_sherry_masterpiece_gold",
        name: "Masterpiece Gold",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Masterpiece Gold",
        composition: "Super 180s Merino Wool",
        weave: "plain",
        pattern: "none",
        colour_family: "navy",
        weight_class: "light",
        ground: "#26304a",
        character: "Super 180s finished to a faint gold shimmer. Cloth for the suit that gets photographed.",
        verified: true,
        source: "https://njb.com.sg/holland-sherry"
    },
    {
        key: "vbc_revenge",
        name: "Revenge",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        bunch: "Revenge",
        composition: "Super 150s Merino Wool",
        weave: "plain",
        pattern: "none",
        colour_family: "charcoal",
        weight_class: "midweight",
        ground: "#3a3b40",
        character: "Fibre no thicker than 16 microns, double-twisted in warp and weft. The twist is what keeps the creases out.",
        verified: true,
        source: "https://njb.com.sg/vitale-barberis-canonico"
    },
    {
        key: "piacenza_prestige_130s",
        name: "Prestige Super 130s",
        mill: "Piacenza",
        millPath: ["cloth_origins", "suiting", "italian", "piacenza"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Prestige Super 130s",
        composition: "Super 130s Wool",
        weave: "twill",
        pattern: "none",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#2b3446",
        character: "Seventeen-micron fibre given a firmer twist. Biella since 1733, and still family-run.",
        verified: true,
        source: "https://njb.com.sg/piacenza-lanificio-cerruti"
    },
    {
        key: "piacenza_alashan_breeze",
        name: "Alashan Breeze",
        mill: "Piacenza",
        millPath: ["cloth_origins", "suiting", "italian", "piacenza"],
        bunch: "Alashan Breeze",
        composition: "Cashmere, Silk and Linen",
        weave: "hopsack",
        pattern: "none",
        colour_family: "cream",
        weight_class: "light",
        ground: "#cec2ac",
        character: "Cashmere, silk and linen, feather-light. The softest thing here that still works in the heat.",
        verified: true,
        source: "https://njb.com.sg/piacenza-lanificio-cerruti"
    },

    // ============================================
    // AUGUST 2026 — pattern and colour range expansion, plus the first
    // houndstooth cloths (weave-engine.js gained a houndstooth overlay
    // for this batch). Researched against real product pages; composition/
    // weight are quoted from source, not invented.
    // ============================================
    {
        key: "fox_houndstooth_classic",
        name: "Classic Flannel Houndstooth, Black & White",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Classic Flannel",
        composition: "100% Superfine Merino Wool",
        weight: "400-430 g",
        weave: "flannel",
        pattern: "houndstooth",
        colour_family: "black",
        weight_class: "heavy",
        ground: "#232325",
        overlay: { type: "houndstooth", colour: "#eae6db", pitch: 8 },
        character: "Fox's own flannel weight in a large black-and-white check, off the archive that dates back to 1772.",
        verified: true,
        source: "https://foxflannel.com/products/classic-flannel-houndstooth-black-white"
    },
    {
        key: "fox_houndstooth_tonal",
        name: "Tonal Houndstooth, Brown & Pink",
        mill: "Fox Brothers",
        millPath: ["cloth_origins", "suiting", "english", "fox"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "100% Wool",
        weight: "480-510 g",
        weave: "twill",
        pattern: "houndstooth",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#4a352c",
        overlay: { type: "houndstooth", colour: "#d9a6a0", pitch: 8 },
        character: "A jacketing weight, the tooth blurred tonal rather than crisp — brown ground, a pink thread turning it up close.",
        verified: true,
        source: "https://foxflannel.com/products/tonal-brown-pink-houndstooth"
    },
    {
        key: "holland_sherry_city_houndstooth",
        name: "City of London Vintage Suiting, Navy Houndstooth",
        mill: "Holland & Sherry",
        millPath: ["cloth_origins", "suiting", "english", "holland_sherry"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "City of London Vintage Suiting",
        composition: "100% Wool",
        weight: "420 g (13.5 oz)",
        weave: "twill",
        pattern: "houndstooth",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#212a40",
        overlay: { type: "houndstooth", colour: "#d6d7db", pitch: 8 },
        character: "Twill, herringbone and birdseye grounds sit in the same book as this houndstooth — the bunch's own idea of a British, tailored look.",
        verified: true,
        source: "https://apparel.hollandandsherry.com/en//6223035-city-of-london-vintage-suiting-navy-houndstooth"
    },
    {
        key: "magee_rockall_houndstooth",
        name: "Rockall Donegal Tweed, Brown Houndstooth",
        mill: "Magee",
        millPath: ["cloth_origins", "suiting", "irish", "magee"],
        guidePath: ["fabrics", "suiting", "summer_tweed"],
        bunch: "Rockall",
        composition: "100% Wool",
        weight: "340 g (12 oz)",
        weave: "twill",
        pattern: "houndstooth",
        colour_family: "brown",
        weight_class: "heavy",
        ground: "#5c4632",
        overlay: { type: "houndstooth", colour: "#cbb89a", pitch: 8 },
        character: "Named for the tiny Atlantic island. Shetland wool, woven at the mill on the River Eske in Donegal Town.",
        verified: true,
        source: "https://magee1866.com/en/Rockall---Brown-Houndstooth-Donegal-Tweed/m-12941.aspx"
    },
    {
        key: "loro_piana_tapa_pinstripe",
        name: "Tapa, Black & Red Pinstripe",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Tapa",
        composition: "Wool and Cashmere",
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "black",
        weight_class: "midweight",
        ground: "#201f22",
        overlay: { type: "pinstripe", colour: "#8a2b2e", pitch: 12 },
        character: "Cashmere in the blend softens what would otherwise be a very sharp black-ground pinstripe.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_fun_chalkstripe",
        name: "Fun, Blue Chalkstripe",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Wool, Super 130s",
        weave: "twill",
        pattern: "chalkstripe",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#2c3e5c",
        overlay: { type: "chalkstripe", colour: "#e8e4d8", pitch: 24 },
        character: "A Super 130s blue ground under a soft, drawn-in-chalk stripe.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_windowpane_grey",
        name: "Natural Grey Windowpane",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Wool",
        weave: "plain",
        pattern: "windowpane",
        colour_family: "grey",
        weight_class: "midweight",
        ground: "#8f8f8a",
        overlay: { type: "windowpane", colour: "#3d3d3a", pitch: 32 },
        character: "Undyed grey wool, a fine windowpane the only decoration.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_pinecone_windowpane",
        name: "Pine Cone, Brown Windowpane",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Wool, Super 130s",
        weave: "twill",
        pattern: "windowpane",
        colour_family: "brown",
        weight_class: "midweight",
        ground: "#5a4530",
        overlay: { type: "windowpane", colour: "#cbb89c", pitch: 32 },
        character: "Warm brown ground, a pale windowpane laid over a Super 130s twill.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_glen_blue",
        name: "Blue Glen Check",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Wool",
        weave: "twill",
        pattern: "glen",
        colour_family: "blue",
        weight_class: "midweight",
        ground: "#2e3c56",
        overlay: { type: "glen", colour: "#c7cbd4", pitch: 24 },
        character: "A blue-ground glen check, plain wool with no fibre claim beyond that.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_timeoff_glen",
        name: "Time Off, Grey Glen Check",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "wool_silk_linen"],
        bunch: "Time Off",
        composition: "Wool, Linen and Silk",
        weave: "hopsack",
        pattern: "glen",
        colour_family: "grey",
        weight_class: "light",
        ground: "#8a8c88",
        overlay: { type: "glen", colour: "#3a3a38", pitch: 24 },
        character: "The casual end of the Loro Piana suiting range — wool, linen and silk in a grey-and-white glen.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_saltbox_birdseye",
        name: "Salt Box, Maroon Birdseye",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "100% Wool",
        weave: "birdseye",
        pattern: "none",
        colour_family: "brown",
        weight_class: "midweight",
        ground: "#3a1f22",
        character: "Maroon and black birdseye — the fleck reads from a distance as a single dark, warm colour.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_tasmanian_pinstripe",
        name: "Tasmanian, Grey Pinstripe",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Tasmanian",
        composition: "Wool, Super 150s",
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "grey",
        weight_class: "light",
        ground: "#6e6e6c",
        overlay: { type: "pinstripe", colour: "#2c2c2a", pitch: 12 },
        character: "The same Tasmanian Super 150s wool as the house's plain cloths, here carrying a fine grey pinstripe.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_australis_pinstripe",
        name: "Australis, Midnight Pinstripe",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Australis",
        composition: "Wool, Super 150s",
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "navy",
        weight_class: "light",
        ground: "#1c2438",
        overlay: { type: "pinstripe", colour: "#c7c9cf", pitch: 12 },
        character: "Australis is the house's Australian merino line — a fine midnight-blue pinstripe off Super 150s wool.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "loro_piana_summertime_windowpane",
        name: "Summertime, Terracotta Windowpane",
        mill: "Loro Piana (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "loro_piana"],
        guidePath: ["fabrics", "suiting", "wool_silk_linen"],
        bunch: "Summertime",
        composition: "Wool, Silk and Linen",
        weave: "hopsack",
        pattern: "windowpane",
        colour_family: "tan",
        weight_class: "light",
        ground: "#a8724f",
        overlay: { type: "windowpane", colour: "#e4d6c4", pitch: 32 },
        character: "Summertime is the warm-weather wool-silk-linen book — terracotta here, with a pale windowpane.",
        verified: true,
        source: "https://www.rexfabrics.com/collections/loro-piana-fabrics"
    },
    {
        key: "solbiati_street_lino_stripe",
        name: "Street Lino, Navy Stripe",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Street Lino",
        composition: "100% Linen",
        weight: "195-200 g",
        weave: "plain",
        pattern: "pinstripe",
        colour_family: "navy",
        weight_class: "light",
        ground: "#232c42",
        overlay: { type: "pinstripe", colour: "#d7d9de", pitch: 12 },
        character: "Aloe vera in the finishing gives Street Lino its soft hand — a striped run off the same bunch as the solids.",
        verified: true,
        source: "https://senszio.com/loro-piana-solbiati-bespoke-tailored-suits-jackets-street-lino-bunch-s13/"
    },
    {
        key: "solbiati_street_lino_check",
        name: "Street Lino, Tan Mini Check",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Street Lino",
        composition: "100% Linen",
        weight: "195-200 g",
        weave: "plain",
        pattern: "windowpane",
        colour_family: "tan",
        weight_class: "light",
        ground: "#c2a883",
        overlay: { type: "windowpane", colour: "#5c4a34", pitch: 24 },
        character: "The mini-check run of Street Lino — the bunch's lightest linen, aloe-softened.",
        verified: true,
        source: "https://senszio.com/loro-piana-solbiati-bespoke-tailored-suits-jackets-street-lino-bunch-s13/"
    },
    {
        key: "solbiati_art_du_lin_olive",
        name: "Art du Lin, Olive",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Art du Lin",
        composition: "100% Linen",
        weight: "410-420 g",
        weave: "plain",
        pattern: "none",
        colour_family: "green",
        weight_class: "heavy",
        ground: "#5c6244",
        character: "Three-ply twisted yarns, springy and raw on the reverse — the same construction as the bunch's tan, in olive.",
        verified: true,
        source: "https://senszio.com/loro-piana-solbiati-bespoke-tailored-suits-jackets-art-du-lin-bunch-s20/"
    },
    {
        key: "solbiati_art_du_lin_navy_heavy",
        name: "Art du Lin, Navy (Heavyweight)",
        mill: "Solbiati (Suiting)",
        millPath: ["cloth_origins", "suiting", "italian", "solbiati"],
        guidePath: ["fabrics", "suiting", "linen_suiting"],
        bunch: "Art du Lin",
        composition: "100% Linen",
        weight: "530 g",
        weave: "hopsack",
        pattern: "none",
        colour_family: "navy",
        weight_class: "heavy",
        ground: "#1f2c46",
        character: "The bunch's heavier weight range — 530 grams of the same twisted three-ply linen, in navy.",
        verified: true,
        source: "https://senszio.com/loro-piana-solbiati-bespoke-tailored-suits-jackets-art-du-lin-bunch-s20/"
    },
    {
        key: "vbc_revenge_windowpane_glen",
        name: "Revenge, Navy Windowpane Glen",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "high_twist_wool"],
        bunch: "Revenge",
        composition: "100% Wool, Super 150s",
        weight: "270 g",
        weave: "twill",
        pattern: "glen",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#1e2740",
        overlay: { type: "glen", colour: "#3a445c", overcheck: "#3a5fae", pitch: 24 },
        character: "A Prince of Wales glen off the same double-twisted Revenge wool, with a royal blue overcheck laid across it.",
        verified: true,
        source: "https://westwoodhart.com/products/vitale-barberis-canonico-revenge-super-150s-made-in-italy-navy-blue-prince-of-wales-glen-plaid-with-royal-blue-windowpane"
    },
    {
        key: "vbc_perennial_windowpane",
        name: "Perennial, Navy Windowpane",
        mill: "VBC",
        millPath: ["cloth_origins", "suiting", "italian", "vbc"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "Perennial",
        composition: "100% Wool Super 110s Worsted",
        weight: "280 g",
        weave: "plain",
        pattern: "windowpane",
        colour_family: "navy",
        weight_class: "midweight",
        ground: "#202b46",
        overlay: { type: "windowpane", colour: "#8890a0", pitch: 32 },
        character: "The same Super 110s as the house's plain Perennial cloth, this run carrying a navy windowpane.",
        verified: true,
        source: "https://westwoodhart.com/products/vitale-barberis-canonico-navy-windowpane-mens-suit"
    },
    {
        key: "drapers_bingley_herringbone",
        name: "The Bingley, Black Herringbone",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        bunch: "The Bingley",
        composition: "Wool, Super 150s",
        weave: "herringbone",
        pattern: "none",
        colour_family: "black",
        weight_class: "midweight",
        ground: "#1c1c1e",
        character: "A jacquard herringbone rather than a woven one — the chevron carried in the loom's own pattern.",
        verified: true,
        source: "https://www.joelandsonfabrics.com/collections/men-brands-drapers"
    },
    {
        key: "drapers_striped_blue",
        name: "Blue Stripe, Super 150s",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Pure Wool, Super 150s",
        weave: "twill",
        pattern: "pinstripe",
        colour_family: "blue",
        weight_class: "light",
        ground: "#2b3f66",
        overlay: { type: "pinstripe", colour: "#dfe1e6", pitch: 12 },
        character: "A straightforward Super 150s stripe — no bunch name given, just the fibre and the fineness.",
        verified: true,
        source: "https://www.joelandsonfabrics.com/collections/men-suiting-pinstripe-fabric"
    },
    {
        key: "drapers_graph_check_teal",
        name: "Graph Check, Dark Teal",
        mill: "Drapers",
        millPath: ["cloth_origins", "suiting", "italian", "drapers"],
        guidePath: ["fabrics", "suiting", "worsted_wool"],
        composition: "Pure Wool",
        weave: "twill",
        pattern: "windowpane",
        colour_family: "green",
        weight_class: "midweight",
        ground: "#1f4a4a",
        overlay: { type: "windowpane", colour: "#bcd8d4", pitch: 32 },
        character: "A graph-paper check in dark teal — closer to green than blue up close.",
        verified: true,
        source: "https://www.joelandsonfabrics.com/collections/men-brands-drapers"
    }
];

if (typeof module !== "undefined" && module.exports) {
    module.exports = { CLOTH_LIBRARY: CLOTH_LIBRARY };
}
